### ISSUE TITLE
[question] Is possible to use Brute LSM in Kernel 5.10 LTS?

### ISSUE THREAD

**Issue by ionutnechita** [johwood/linux#1]
Hi @johwood,

I observe this: Brute LSM. I like this.
Is possible to use Brute LSM in Kernel 5.10 LTS, with porting brute_v7 to latest 5.10?

Thanks.

**Comment by johwood** [comment]
I think so. This LSM is not based in any specific feature. I believe that the rebase is simple enough.

But warning: the Brute LSM is under review in the path to the mainline :)
https://lore.kernel.org/kernel-hardening/20210521172414.69456-1-john.wood@gmx.com/

So, its a "work in progress" LSM.

Thanks for the interest.

**Comment by ionutnechita** [comment]
Hi @johwood,

Thanks for answer.

**Comment by ionutnechita** [comment]
It's fine to close this ticket.
